services:
  web:
    build: ./fe
    networks:
      - app-network
    ports:
      - "5002:5002"
    depends_on:
      - backend-service
    environment:
      BACKEND_API_URL: http://backend-service:5001/fetch_price

  backend-service:
    build: ./be
    networks:
      - app-network
    depends_on:
      - mysqldb
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: 123456

  mysqldb:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: crypto_db
    networks:
      - app-network

networks:
  app-network: